### PR TITLE
[tests]: test for half of Number-theoretic and representation funcs (#2)

### PR DESCRIPTION
**Pull request by paulolimac**
Addresses #2 , partially.

Implements some unit tests to 'Number-theoretic and representation' functions (7 or 8 of them).

For more info, see commits.

### CODE REVIEW

**Comment by ElecProg** [comment]
This is very welcome! To be honest I should probably extend the amount of testing done on the other parts...

Again thank you very much!

**Comment by ElecProg** [comment]
A quick apology: DecMath is always meant to return a Decimal (hence the name) I do not know why I wrote float instead of Decimal in the documentation of `copysign`...

**Comment by paulolimac** [comment]
No problem.
I asserted with 'int' and 'float' in most of the cases, but is a good thing to extend with Decimal too (it is the lib's default).

I had some difficult to figure out all possible combinations-cases for the parameters. In a numeric-math-phisics-enge lib, I think the tests needs to be as exhaustive as possible and it results in the hardwork.

Keep working!

**Comment by ElecProg** [comment]
As a followup on this pull request, all previously failing test cases now complete successfully.

**Pull request merged**
